name: Update Lock File

on:
  push:
    paths:
      - 'package.json'

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies and Update Lockfile
        run: |
          npm install

      - name: Commit updated lockfile
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update package-lock.json after deps bump'
